### ISSUE TITLE
How exactly can we use the multi-node version

### ISSUE THREAD

**Issue by cshanbo** [mila-udem/platoon#89]
Hi,
I wanted to run the example code (lstm) on **multi-node** but got stuck.

I've read the ```platoon-launcher -h``` and ```platoonrc.conf```, but I still cannot figure out how to configure the multi-node version.
here are some questions from me:

1. how to use the platoonrc file? I mean like which path to put it into, 
2. how to specify the platoonrc path in command line with ```platoon-launcher```?  I've read the help doc, but got no luck.

An example of lstm training on multi-node, multi-card version, or more detailed readme would be much more helpful. 

Thank you.

**Comment by tsirif** [comment]
Can you give me an example of your infrastructure? How many hosts there
will be? How many GPUs are expected to be used per host? Are directories
shared among nodes in infrastructure's setup? How do nodes communicate with
each other?

I am asking the latter because there is an issue in Platoon with
infrastructures using infiniband. [OpenMPI does not (always) allow forking
subprocesses in each MPI process respectively in order to create necessary
workers per node.
https://www.open-mpi.org/faq/?category=openfabrics#ofa-fork]

**Comment by kobecsb** [comment]
Hi @tsirif , thank you for your help I will try my best to give you detailed information. .

1. you can  assume that I have 2 hosts, and 7 GPUs/ host. 

2. Did you mean the directory organization? You can assume that my directory structures are same among each node. But I think multiple nodes cannot share the same directory of one specific node, is that right? 
   > Are directories shared among nodes in infrastructure's setup? 

3. I implemented a controller and a worker for my project, and it works fine on single node. I thought platoon will do the communication between nodes. Did I misunderstand?  I want to run multi-node lstm (in ```example``` directory of platoon) first if it's possible, then transfer to my own project.
   > How do nodes communicate with each other?

**Comment by tsirif** [comment]
1.

   you can assume that I have 2 hosts, and 7 GPUs/ host.

Wonderful.


   1.

   Did you mean the directory organization? You can assume that my
   directory structures are same among each node. But I think multiple nodes
   cannot share the same directory of one specific node, is that right?

In cluster infrastructures it is common for nodes to share the [same file
system](https://en.m.wikipedia.org/wiki/Clustered_file_system). I think
that same directory structure will suffice though.


   1.

   I implemented a controller and a worker for my project, and it works
   fine on single node. I thought platoon will do the communication between
   nodes. Did I misunderstand? I want to run multi-node lstm (in example
   directory of platoon) first if it's possible, then transfer to my own
   project.

Yes, Platoon should use automatically use MPI given appropriate
configuration. What I mean though by communication model is what is the
hardware/software interface (physical and low level) that you use in your
case, e.g. ethernet or infiniband interconnected nodes. I ask about this
because there would be probably problems with current Platoon if you are
using infiniband.

In any case, I am available to try along with you and fix whatever problems
may exist in Platoon. Note that multi-node usage is not yet properly
tested, but if you are willing to try it, I will be happy to make it stable
with your feedback.

**Comment by tsirif** [comment]
For starters if you want to try using every GPU in each node, you can use `-H` argument at `platoon-launcher`, e.g. `platoon-launcher lstm -H hostname0 hostname1`.

**Comment by kobecsb** [comment]
Hi @tsirif . I used ```platoon-launcher lstm -H hostname0 hostname1``` to test the multi-node version after I installed openmpi on both nodes.
But an error encountered like (googled but got no luck):
```
### Launching experiment: lstm
### Starting multi-node/gpu training on: nmyjs_104_22 nmyjs_104_37 ... Done

### Logs folder ###
PLATOON_LOGS/lstm/2017-02-17_10-57-44

### Waiting on experiment to finish ...

[nmyjs_104_37:29342] [[62196,0],1] ORTE_ERROR_LOG: File open failure in file iof_orted.c at line 180
[nmyjs_104_37:29342] [[62196,0],1] ORTE_ERROR_LOG: File open failure in file base/iof_base_setup.c at line 224
[nmyjs_104_37:29342] [[62196,0],1] ORTE_ERROR_LOG: File open failure in file odls_default_module.c at line 525
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 29366 on node nmyjs_104_37 exited on signal 85 (Unknown signal 85).
--------------------------------------------------------------------------
## Multi-node Controllers terminated with return code: 213.

ERROR! An error has occured.
See logs for more info.
```
And the log is empty.
I'm wondering whether it is caused by dependency installation mistake or any other reason.

**Comment by cshanbo** [comment]
```
Cannot call MPI_INIT or MPI_INIT_THREAD more than once while being in multi-node mode MPI_Init(156): Cannot call MPI_INIT or MPI_INIT_THREAD more than once while being in multi-node mode MPI_Init(156): Cannot call MPI_INIT or MPI_INIT_THREAD more than once while being in multi-node mode
```
Does this means that I installed openmpi in a wrong way?

**Comment by tsirif** [comment]
The same problem occured to me months before when I wrote this. I suppose
that forking from multi-node MPI processes implicitly means that they are
considered MPI processes too (?)... which is not useful in our case since
workers are using inter-GPU communication separate from MPI. I will look
into this tomorrow, I will let you know if there is any progress. I will
try to spawn workers as if they were dynamically created MPI processes
through openMPI API instead of forking.

**Comment by cshanbo** [comment]
Thank you @tsirif . I will try my best to see if there's solution, too.

**Comment by cshanbo** [comment]
Hi @tsirif . I think the error might be caused by the designing of controller.
As in multi-node scenario, we will invoke num_nodes controllers, each on one node.
But in each controller, an ```MPI.init()``` function is called, which is not allowed in MPI.

**Comment by tsirif** [comment]
Yes, I think you are right. For the attempt to fix this, please refer to [this branch](https://github.com/tsirif/platoon/tree/fix/multi-node).

**Comment by cshanbo** [comment]
Hi @tsirif 

I tried your new branch, but still got errors like:

```
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nmyjs_104_37:13984] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)

```

I'm not sure whether you've tested successfully on your own nodes. I think this error might be caused by the mis-installation of openmpi? Could you please tell me the ```MPI``` version you used?

Thank you.

**Comment by cshanbo** [comment]
It seems the controller was triggered, but interrupted by some error.

**Comment by tsirif** [comment]
Hi there @cshanbo, I pushed something (untested) in the direction of solving the **known** bug of launching workers in multi-node (when using openMPI+infiniband), but as far as I can understand this is not the case from your output. This is something I have not seen yet. I have not tested Platoon thoroughly in multi-node. Sorry, for the inconvenience, I hope we can solve this. I use openMPI 1.10.0.

Let's try something simpler than lstm. Can you please, run tests in `platoon/tests/functional` and provide me with output/error bins of script/controllers/workers?
i.e.
```
export PLATOON_TEST_WORKERS_NUM=<num_of_gpus_you_expect_to_use>
platoon-launcher test -H <host1> <host2>
```

You can also write a config file and launch with `platoon-launcher test`. For example to use 2 gpus on each of your hosts, you can write a file and save it as `.platoonrc` in the directory where you will execute the tests:
```
[platoon]
hosts : nmyjs_104_37, nmyjs_104_22
 
[devices]
nmyjs_104_37 : cuda0, cuda1
nmyjs_104_22 : cuda0, cuda1
```

Also, just to cross-out possibilities, have you tried a simple running a simple MPI demo? 

P.S. Please do not edit your comments, post new ones instead, because it seems that github does not notify for edits in posts.

**Comment by cshanbo** [comment]
HI. Yes, i tried simpler examples in mpi4py demo directory. And it works. i will follow your suggestion today and reply to you asap. Sorry for the late reply due to the jet lag between us.

**Comment by cshanbo** [comment]
Hi @tsirif . I did some tests on [your new branch](https://github.com/tsirif/platoon), and got these results.

1. First attemption

When I exported `PLATOON_TEST_WORKERS_NUM` and run platoon-launcher test -H host1 host2
The error is:
```
### Launching experiment: test
### Starting single-node multi-gpu training

ERROR! A single host 'nmyjs_104_22,nmyjs_104_37' was specified which is not the same as the current host 'nmyjs_104_22'.
This is not currently supported.
[@nmyjs_104_22 functional]$ platoon-launcher test -H nmyjs_104_22 nmyjs_104_37
### Launching experiment: test
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[2590,1],0] (PID 54027)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
### Starting multi-node/gpu training on: nmyjs_104_22 nmyjs_104_37 ... Done

### Logs folder ###
PLATOON_LOGS/test/2017-02-23_10-18-18

### Waiting on experiment to finish ...
chengshanbo@nmyjs_104_37's password: 
[nmyjs_104_37:54020] [[2565,0],1] ORTE_ERROR_LOG: File open failure in file iof_orted.c at line 180
[nmyjs_104_37:54020] [[2565,0],1] ORTE_ERROR_LOG: File open failure in file base/iof_base_setup.c at line 224
[nmyjs_104_37:54020] [[2565,0],1] ORTE_ERROR_LOG: File open failure in file odls_default_module.c at line 525
[nmyjs_104_22:54039] [[2565,0],0] usock_peer_send_blocking: send() to socket 40 failed: Broken pipe (32)
[nmyjs_104_22:54039] [[2565,0],0] ORTE_ERROR_LOG: Unreachable in file oob_usock_connection.c at line 315
[nmyjs_104_22:54039] [[2565,0],0]-[[2565,1],0] usock_peer_accept: usock_peer_send_connect_ack failed
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 54044 on node nmyjs_104_37 exited on signal 85 (Unknown signal 85).
--------------------------------------------------------------------------
## Multi-node Controllers terminated with return code: 213.

ERROR! An error has occured.
See logs for more info.
```
Which is still caused by the `--output-filename` option in mpirun. It should work, but I'm not sure why this error happens. 


2. second attemption

I fixed this error by removing  the `--output-filename` option and I got this error:
```
WARNING! Using all compatible GPUs in nmyjs_104_22.
WARNING! Using all compatible GPUs in nmyjs_104_37.
WARNING! Found 8 GPUs!
## On nmyjs_104_22 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
WARNING! Found 8 GPUs!
## On nmyjs_104_37 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
ERROR! While spawning workers through MPI: global name 'launch_mpi_workers' is not defined
ERROR! While spawning workers through MPI: global name 'launch_mpi_workers' is not defined
```

I fixed this by adding `launch_mpi_workers` in controller.py (import), and got the following error.

3. third attemption
```
## On nmyjs_104_22 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
WARNING! Found 8 GPUs!
WARNING! Found 8 GPUs!
## On nmyjs_104_37 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
ERROR! While spawning workers through MPI: global name 'self' is not defined
ERROR! While spawning workers through MPI: global name 'self' is not defined
```
I fixed this by pass adding an argument in `launch_mpi_workers` function, and got the following error.

4. fourth attemption
```
WARNING! Using all compatible GPUs in nmyjs_104_22.
WARNING! Using all compatible GPUs in nmyjs_104_37.
WARNING! Found 8 GPUs!
## On nmyjs_104_22 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
WARNING! Found 8 GPUs!
## On nmyjs_104_37 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
ERROR! While spawning workers through MPI: expecting 8 items, got 0
ERROR! While spawning workers through MPI: expecting 8 items, got 0
```
I fixed this by rewrite the codes in controller.py
And got error:
```
There are not enough slots available in the system to satisfy the 1 slots
that were requested by the application:
  /search/odin/chengshanbo/anaconda2/bin/python

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
ERROR! While spawning workers through MPI: MPI_ERR_SPAWN: could not spawn processes
ERROR! While spawning workers through MPI: MPI_ERR_SPAWN: could not spawn processes

```

5. fifth attemption
fixed this by adding `--oversubscribe` option in mpirun. but still got no luck.
```
WARNING! Using all compatible GPUs in nmyjs_104_22.
WARNING! Using all compatible GPUs in nmyjs_104_37.
WARNING! Found 8 GPUs!
## On nmyjs_104_22 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
WARNING! Found 8 GPUs!
## On nmyjs_104_37 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
ERROR! While spawning workers through MPI: ERROR! MPI spawn multi error codes: [[24616720], [0], [24618432], [0], [24616656], [0], [-1533477160], [61]]
ERROR! While spawning workers through MPI: ERROR! MPI spawn multi error codes: [[57725280], [0], [57726992], [0], [57725216], [0], [530120408], [49]]
[nmyjs_104_22:01760] [[57330,0],0] ORTE_ERROR_LOG: Not found in file orted/pmix/pmix_server_dyn.c at line 87
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
could not find = char
-------------------------------------------------------

```
I assume this is a mpirun error which I'm not familiar with.
The modifications so far could be seen in [my forked repo](https://github.com/cshanbo/platoon.git), fix/multi-node branch. Maybe I will set a PR.

**Comment by cshanbo** [comment]
I used the [previous version]()  of your fix/multi-node branch to run the 'test' exp in functional. And it still got the same error as:
```
### Launching experiment: test
### Starting multi-node/gpu training on: nmyjs_104_22 nmyjs_104_37 ... Done

### Logs folder ###
PLATOON_LOGS/test/2017-02-23_11-23-23

### Waiting on experiment to finish ...
chengshanbo@nmyjs_104_37's password: 
WARNING! Using all compatible GPUs in nmyjs_104_22.
WARNING! Found 8 GPUs!
## On nmyjs_104_22 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
WARNING! Using all compatible GPUs in nmyjs_104_37.
WARNING! Found 8 GPUs!
## On nmyjs_104_37 using: cuda0 cuda1 cuda2 cuda3 cuda4 cuda5 cuda6 cuda7
## Running in multi-node mode.
## Starting worker on cuda0 ... Done
## Starting worker on cuda1 ... Done
## Starting worker on cuda2 ... Done
## Starting worker on cuda0 ... ## Starting worker on cuda3 ... Done
## Starting worker on cuda4 ... Done
## Starting worker on cuda5 ... Done
## Starting worker on cuda1 ... Done
## Starting worker on cuda6 ... Done
## Starting worker on cuda7 ... Done
## Starting worker on cuda2 ... Done
Done
## Starting worker on cuda3 ... Done
## Starting worker on cuda4 ... Done
## Starting worker on cuda5 ... Done
## Starting worker on cuda6 ... Done
## Starting worker on cuda7 ... Done
Caught signal 15. Killing workers and closing connections...
Killing worker 39362...
Killing worker 39363...
Killing worker 39364...
Killing worker 39365...
## Multi-node Controllers terminated with return code: 65.


*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nmyjs_104_22:43966] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)

```

### I will try your openmpi version to test and give your the information.

**Comment by cshanbo** [comment]
BTW, I tested the helloworld.py in mpi4py/demo like:
```
mpirun -np2 -H nmyjs_104_22,nmyjs_104_37 python helloworld.py
```
And it works fine and the output is 
```
Hello, World! I am process 0 of 2 on nmyjs_104_22.
Hello, World! I am process 1 of 2 on nmyjs_104_37.
```

PS: helloworld.py is like:
```
#!/usr/bin/env python
"""
Parallel Hello World
"""

from mpi4py import MPI
import sys

size = MPI.COMM_WORLD.Get_size()
rank = MPI.COMM_WORLD.Get_rank()
name = MPI.Get_processor_name()

sys.stdout.write(
    "Hello, World! I am process %d of %d on %s.\n"
    % (rank, size, name))
```
So I think my installation of openmpi and mpi4py should be fine.

**Comment by cshanbo** [comment]
I thought it should be the error caused by platoon itself, rather than mpirun.
Maybe we should check the codes.

**Comment by tsirif** [comment]
Yes, we should. Would you like to do a hackathon to fix this? I propose
this because it's difficult to communicate due to the differences of our
timezones and because I lack immediate access to multi-node/gpu machine.
Although I can submit jobs in a cluster, there is much delay in the queues
for this to be tested and solved quickly in that case.

Email me at tsirif [at] gmail (dot) com

**Comment by cshanbo** [comment]
Hackathon is a great idea. But I have to work in day time on working days (Beijing time), so it might be a little difficult for me. I feel sorry about this. But sure I'll do my best to support you. Or we can set a time that suits both of us.  You can email me cshanbo [at] gmail [dot] com anytime you want.

**Comment by cshanbo** [comment]
And I looked into the codes early today. The `query = self.csocket.recv_json(flag=zmq.NOBLCK)` seems to get timeout (keep raise zmq,Again error multiple times, then fail). Maybe it is binded (`self.csocket.bind('tcp://*:{}'.format(port))`) to the wrong port in multi-node version? Maybe two different nodes uses different ports? Just a simple guess.

**Comment by tsirif** [comment]
Yes you are totally correct! Each node should use ZMQ for intranode
communication only. Should we perhaps specify tcp address to be something
like "tcp://localhost:{port}" and keep the same port across all hosts?
Would that resolve the problem? We could try another communication protocol
with ZMQ that would work only intranode-ly, i.e. inter process transport
(ipc).
http://api.zeromq.org/2-1:zmq-ipc
This will probably also have a time advantage too.

**Comment by cshanbo** [comment]
Hi @tsirif  .
I'll look into this issue today. BTW, I should be free tomorrow since it's Saturday in China. If you  need some help, just email me whenever you want.
